feat: Upgrade to SDK v4
coinpaprika/cq-source-coinpaprika pull request #7
Opened 2023-11-01 14:03 UTC by maaarcelino

Hi there! This is a PR to update to our latest SDK! We are also rolling out hub shortly - https://hub.cloudquery.io so, once this PR is approved we can follow-up with additional PR so publish the plugin to our hub so users can enjoy dynamic searchable documentation for all versions and all tables.

2023-11-01 14:37 UTC, candiduslynx requested changes

2023-11-01 14:37 UTC, candiduslynx commented on plugin/plugin.go
> +	Name    = "coinpaprika-coinpaprika"
```suggestion
	Name    = "coinpaprika"
```

2023-11-01 14:37 UTC, candiduslynx commented on resources/services/coins/tickers.go
> +		value, err := cl.Backend.GetKey(ctx, key)
IMO you could just use state.NopClient & never perform the `if cl.Backend != nil` check

2023-11-01 14:37 UTC, candiduslynx commented on resources/services/coins/tickers.go
> +		err = cl.Backend.Flush(ctx)
no need to perform manual flush, done in `plugin.Client.Sync`

2023-11-01 14:37 UTC, candiduslynx commented on plugin/client.go
> +	backendConn *grpc.ClientConn
```suggestion
```

2023-11-01 14:37 UTC, candiduslynx commented on plugin/client.go
> +	}
```suggestion
```

2023-11-01 14:37 UTC, candiduslynx commented on plugin/client.go
> +	tt, err := c.tables.FilterDfs(options.Tables, options.SkipTables, options.SkipDependentTables)
verify for no connection, see https://github.com/cloudquery/cloudquery/blob/main/plugins/source/gcp/resources/plugin/client.go

2023-11-01 14:37 UTC, candiduslynx commented on plugin/client.go
> +	}
```suggestion
	stateClient := state.Client(&state.NoOpClient{})
	if options.BackendOptions != nil {
		conn, err := grpc.DialContext(ctx, options.BackendOptions.Connection,
			grpc.WithTransportCredentials(insecure.NewCredentials()),
			grpc.WithDefaultCallOptions(
				grpc.MaxCallRecvMsgSize(maxMsgSize),
				grpc.MaxCallSendMsgSize(maxMsgSize),
			),
		)
		if err != nil {
			return fmt.Errorf("failed to dial grpc destination plugin at %s: %w", options.BackendOptions.Connection, err)
		}
		stateClient, err = state.NewClient(ctx, conn, options.BackendOptions.TableName)
		if err != nil {
			return fmt.Errorf("failed to create state client: %w", err)
		}
	}
```

2023-11-01 14:54 UTC, maaarcelino commented on plugin/client.go
> +	backendConn *grpc.ClientConn
Done in f40bcbd

2023-11-01 14:54 UTC, maaarcelino commented on plugin/client.go
> +	}
Done in f40bcbd

2023-11-01 14:54 UTC, maaarcelino commented on plugin/client.go
> +	}
Done in f40bcbd

2023-11-01 15:21 UTC, candiduslynx requested changes

2023-11-01 15:21 UTC, candiduslynx commented on resources/services/coins/tickers.go
> +		value, err := cl.Backend.GetKey(ctx, key)
still here

2023-11-01 15:21 UTC, candiduslynx commented on resources/services/coins/tickers.go
> +		err = cl.Backend.SetKey(ctx, key, upTo.Format(time.RFC3339))
remove `if cl.Backend != nil` check

2023-11-01 15:40 UTC, candiduslynx approved these changes

2023-11-01 16:09 UTC, candiduslynx commented
cc: @mbillewicz @r--w

2023-11-02 13:33 UTC, r--w commented
Wow, thanks for this contribution; it seems like you spent some time on this PR. We will review the code within a week.

2023-11-02 13:48 UTC, r--w commented
Hey @candiduslynx & @maaarcelino could you fix the [quality/linter issues](https://github.com/coinpaprika/cq-source-coinpaprika/actions/runs/6721680700/job/18301755791?pr=7#step:4:25)?

You can run this command locally `make check`

2023-11-03 11:07 UTC, maaarcelino commented
@r--w There's only a `make lint` command which passes for me locally without making any changes. Those logs appear to point to some other code (e.g. `deleteValue` is not present in any of the files in this repo). 

There were a few failing tests due to a nil pointer and I've fixed those. Now both `make lint` and `make test` all pass.

2023-11-03 12:49 UTC, mbillewicz commented
Try to update linter in .github/workflows/test.yaml line 26 to latest version.

2023-11-03 13:21 UTC, maaarcelino commented
@mbillewicz Updated to 1.55.1

2023-11-04 21:13 UTC, mbillewicz commented
@maaarcelino  pls also regenerate files by  `make gen` due to failing workflow test job

2023-11-06 12:35 UTC, merged